spring.application.name: api-gateway
server.port: 8081

eureka.client.service-url.defaultZone: http://localhost:8761/eureka
jwt.secretKey: a-string-secret-at-least-256-bits-long

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2
            - id: posts-service
              uri: lb://POSTS-SERVICE
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter
            - id: connections-service
              uri: lb://CONNECTION-SERVICE
              predicates:
                - Path=/api/v1/connections/**
              filters:
                 - StripPrefix=2
                 - name: AuthenticationFilter

