kafka.topic:
  post-created-topic: post-created-topic
  post-liked-topic: post-liked-topic

spring:
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema:
          registry:
            url: "http://127.0.0.1:8081"